export const Users = [
  {
    "id": 3350606,
    "wikiDataId": "Q24668",
    "type": "CITY",
    "city": "Aixirivall",
    "name": "Aixirivall",
    "country": "Andorra",
    "countryCode": "AA",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.46245,
    "longitude": 1.50209,
    "population": 0
  },
  {
    "id": 3216144,
    "wikiDataId": "Q24656",
    "type": "CITY",
    "city": "Aixovall",
    "name": "Aixovall",
    "country": "Andorra",
    "countryCode": "AB",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.47635833,
    "longitude": 1.48949167,
    "population": 0
  },
  {
    "id": 3406038,
    "wikiDataId": "Q4699394",
    "type": "CITY",
    "city": "Aixàs",
    "name": "Aixàs",
    "country": "Andorra",
    "countryCode": "AC",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.48638889,
    "longitude": 1.46722222,
    "population": 0
  },
  {
    "id": 397,
    "wikiDataId": "Q1863",
    "type": "CITY",
    "city": "Andorra la Vella",
    "name": "Andorra la Vella",
    "country": "Andorra",
    "countryCode": "AD",
    "region": "Andorra la Vella",
    "regionCode": "07",
    "latitude": 42.5,
    "longitude": 1.5,
    "population": 22151
  },
  {
    "id": 3360277,
    "wikiDataId": "Q24475",
    "type": "CITY",
    "city": "Ansalonga",
    "name": "Ansalonga",
    "country": "Andorra",
    "countryCode": "AE",
    "region": "Ordino",
    "regionCode": "05",
    "latitude": 42.568443,
    "longitude": 1.521571,
    "population": 0
  },
  {
    "id": 3350606,
    "wikiDataId": "Q24668",
    "type": "CITY",
    "city": "Aixirivall",
    "name": "Aixirivall",
    "country": "Andorra",
    "countryCode": "AF",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.46245,
    "longitude": 1.50209,
    "population": 0
  },
  {
    "id": 3216144,
    "wikiDataId": "Q24656",
    "type": "CITY",
    "city": "Aixovall",
    "name": "Aixovall",
    "country": "Andorra",
    "countryCode": "AG",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.47635833,
    "longitude": 1.48949167,
    "population": 0
  },
  {
    "id": 3406038,
    "wikiDataId": "Q4699394",
    "type": "CITY",
    "city": "Aixàs",
    "name": "Aixàs",
    "country": "Andorra",
    "countryCode": "AH",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.48638889,
    "longitude": 1.46722222,
    "population": 0
  },
  {
    "id": 397,
    "wikiDataId": "Q1863",
    "type": "CITY",
    "city": "Andorra la Vella",
    "name": "Andorra la Vella",
    "country": "Andorra",
    "countryCode": "AI",
    "region": "Andorra la Vella",
    "regionCode": "07",
    "latitude": 42.5,
    "longitude": 1.5,
    "population": 22151
  },
  {
    "id": 3360277,
    "wikiDataId": "Q24475",
    "type": "CITY",
    "city": "Ansalonga",
    "name": "Ansalonga",
    "country": "Andorra",
    "countryCode": "AJ",
    "region": "Ordino",
    "regionCode": "05",
    "latitude": 42.568443,
    "longitude": 1.521571,
    "population": 0
  },
  {
    "id": 3350606,
    "wikiDataId": "Q24668",
    "type": "CITY",
    "city": "Aixirivall",
    "name": "Aixirivall",
    "country": "Andorra",
    "countryCode": "AK",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.46245,
    "longitude": 1.50209,
    "population": 0
  },
  {
    "id": 3216144,
    "wikiDataId": "Q24656",
    "type": "CITY",
    "city": "Aixovall",
    "name": "Aixovall",
    "country": "Andorra",
    "countryCode": "AL",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.47635833,
    "longitude": 1.48949167,
    "population": 0
  },
  {
    "id": 3406038,
    "wikiDataId": "Q4699394",
    "type": "CITY",
    "city": "Aixàs",
    "name": "Aixàs",
    "country": "Andorra",
    "countryCode": "AM",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.48638889,
    "longitude": 1.46722222,
    "population": 0
  },
  {
    "id": 397,
    "wikiDataId": "Q1863",
    "type": "CITY",
    "city": "Andorra la Vella",
    "name": "Andorra la Vella",
    "country": "Andorra",
    "countryCode": "AN",
    "region": "Andorra la Vella",
    "regionCode": "07",
    "latitude": 42.5,
    "longitude": 1.5,
    "population": 22151
  },
  {
    "id": 3360277,
    "wikiDataId": "Q24475",
    "type": "CITY",
    "city": "Ansalonga",
    "name": "Ansalonga",
    "country": "Andorra",
    "countryCode": "AO",
    "region": "Ordino",
    "regionCode": "05",
    "latitude": 42.568443,
    "longitude": 1.521571,
    "population": 0
  },
  {
    "id": 3350606,
    "wikiDataId": "Q24668",
    "type": "CITY",
    "city": "Aixirivall",
    "name": "Aixirivall",
    "country": "Andorra",
    "countryCode": "AP",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.46245,
    "longitude": 1.50209,
    "population": 0
  },
  {
    "id": 3216144,
    "wikiDataId": "Q24656",
    "type": "CITY",
    "city": "Aixovall",
    "name": "Aixovall",
    "country": "Andorra",
    "countryCode": "AQ",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.47635833,
    "longitude": 1.48949167,
    "population": 0
  },
  {
    "id": 3406038,
    "wikiDataId": "Q4699394",
    "type": "CITY",
    "city": "Aixàs",
    "name": "Aixàs",
    "country": "Andorra",
    "countryCode": "AR",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.48638889,
    "longitude": 1.46722222,
    "population": 0
  },
  {
    "id": 397,
    "wikiDataId": "Q1863",
    "type": "CITY",
    "city": "Andorra la Vella",
    "name": "Andorra la Vella",
    "country": "Andorra",
    "countryCode": "AS",
    "region": "Andorra la Vella",
    "regionCode": "07",
    "latitude": 42.5,
    "longitude": 1.5,
    "population": 22151
  },
  {
    "id": 3360277,
    "wikiDataId": "Q24475",
    "type": "CITY",
    "city": "Ansalonga",
    "name": "Ansalonga",
    "country": "Andorra",
    "countryCode": "AT",
    "region": "Ordino",
    "regionCode": "05",
    "latitude": 42.568443,
    "longitude": 1.521571,
    "population": 0
  },
  {
    "id": 3350606,
    "wikiDataId": "Q24668",
    "type": "CITY",
    "city": "Aixirivall",
    "name": "Aixirivall",
    "country": "Andorra",
    "countryCode": "AU",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.46245,
    "longitude": 1.50209,
    "population": 0
  },
  {
    "id": 3216144,
    "wikiDataId": "Q24656",
    "type": "CITY",
    "city": "Aixovall",
    "name": "Aixovall",
    "country": "Andorra",
    "countryCode": "AV",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.47635833,
    "longitude": 1.48949167,
    "population": 0
  },
  {
    "id": 3406038,
    "wikiDataId": "Q4699394",
    "type": "CITY",
    "city": "Aixàs",
    "name": "Aixàs",
    "country": "Andorra",
    "countryCode": "AW",
    "region": "Sant Julià de Lòria",
    "regionCode": "06",
    "latitude": 42.48638889,
    "longitude": 1.46722222,
    "population": 0
  },
  {
    "id": 397,
    "wikiDataId": "Q1863",
    "type": "CITY",
    "city": "Andorra la Vella",
    "name": "Andorra la Vella",
    "country": "Andorra",
    "countryCode": "AX",
    "region": "Andorra la Vella",
    "regionCode": "07",
    "latitude": 42.5,
    "longitude": 1.5,
    "population": 22151
  },
  {
    "id": 3360277,
    "wikiDataId": "Q24475",
    "type": "CITY",
    "city": "Ansalonga",
    "name": "Ansalonga",
    "country": "Andorra",
    "countryCode": "AY",
    "region": "Ordino",
    "regionCode": "05",
    "latitude": 42.568443,
    "longitude": 1.521571,
    "population": 0
  },
  {
    "id": 3360277,
    "wikiDataId": "Q24475",
    "type": "CITY",
    "city": "Ansalonga",
    "name": "Ansalonga",
    "country": "Andorra",
    "countryCode": "AZ",
    "region": "Ordino",
    "regionCode": "05",
    "latitude": 42.568443,
    "longitude": 1.521571,
    "population": 0
  }
]
